### ISSUE TITLE
JarasInd kérdés

### ISSUE THREAD

**Issue by ginyor** [tamas-ferenci/MagyarorszagKozutiElerhetoseg#1]
Szia,

nagyon hasznosnak találom és próbálnám egy picit átalakítani, hogy a számomra is hasznos legyene, de a JarasInd változó az mit "takar", illetve hogyan képződik kód szinten?

Előre is köszönöm a válaszod.

Üdv,
Gábor

**Comment by ferenci-tamas** [comment]
Szia!

Igen, ez kicsit cseles, mert csak akkor látszik, ha az ember az [Rmd fájlba](https://github.com/tamas-ferenci/MagyarorszagKozutiElerhetoseg/blob/main/README.Rmd) is belenéz (a kimenetbe be nem rakott előkészítő kódblokkban van). Kiemelem a lényeget:

`JarasInd <- (HNTdata$Helység.megnevezése==HNTdata$Járás.székhelye)|(HNTdata$Megye.megnevezése=="főváros")`

Magyarán ez a változó azt jelzi, hogy az adott helység járás székhelye-e (így tekintve a budapesti kerületeket is). Ez azért érdekes, mert a kórházak telepítését csak járási székhelyekkel próbálgatom végig ("Élhetünk azzal az egyszerűsítéssel, hogy kórházat csak járási székhelyre telepítünk"), így ez a változó jelöli ki, hogy mely településeket kell ezen vizsgálat során használni.

**Comment by ginyor** [comment]
Szia,

nagyon köszönöm a választ.

Így jött a következő probléma a captionlab.

Tudnál benne segíteni?

Előre is nagyon köszönöm.

**Comment by ferenci-tamas** [comment]
Hogyne, különösen, mert ez ugyanez pepitában:

`captionlab <- paste0("Ferenci Tamás, http://www.medstat.hu/\nhttps://github.com/tamas-ferenci/",
                     "MagyarorszagKozutiElerhetoseg")`

Lehet, hogy érdemes megnézned ezt az egész kódblokkot (különösen, mert azt hiszem más blokk nincs, ami ne szerepelne a fájlban):

https://github.com/tamas-ferenci/MagyarorszagKozutiElerhetoseg/blob/b21b29f613dcb96413558a796ee88b488dfc3f75/README.Rmd#L15-L40

Szóval ha minden igaz, ez megválaszolja az összes többi potenciális, hasonló kérdést is.

**Comment by ginyor** [comment]
Szia,

köszönöm ismét.

Sajnos az R nem az erősségem és át szeretném írni úgy a kkorhazplotot, hogy csak bizonyos vármegyeszékhelyek szerepeljenek kb.: 10db (Budapest, Szeged, Pécs, Győr...) és ne fix-en 50db.

Remlélem tudsz benne segíteni és az időd is engedi.

Üdv,
Gábor

**Comment by ferenci-tamas** [comment]
Nem ellenőriztem le ténylegesen (kód-futtatással), de első blikkre azt mondanám, hogy ez épp a `JarasInd`-del oldható meg a legegyszerűbben: ha átállítod, hogy csak az általad "engedélyezett" településeken legyen `TRUE` az értéke, és úgy futtatod újra, akkor -- ha nem tévedek -- úgy fog lefutni a keresés, hogy csak oda próbálkozik kórházat rakni.
